site_name: KnowHow Base
repo_url: https://github.com/mkapra/KnowHow-Base
repo_name: mkapra/Knowhow-Base
edit_uri: edit/main/docs/

nav:
  - index.md
  - FiSi:
    - ISO/OSI: 'fisi/isoosi.md'
    - RAID: 'fisi/raid.md'
    - SNMP: 'fisi/snmp.md'
    - USV: 'fisi/usv.md'
    - Nice2Know Ports: 'fisi/ports.md'
    - Glossar: 'fisi/glossar.md'

theme:
  name: material
  language: de
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - navigation.expand

markdown_extensions:
  - footnotes
  - tables
